name: Build and Test

on: [ push ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
        with:
          python-version: '3.14'
          # cache: 'pipenv' # caching pipenv dependencies
      - name: Install uv and pipx
        run: |
          pip install uv && pip install pipx && uv sync && make check
